%% create_model3.m — Construit le modèle Simulink simul3 (chaîne avec défauts)
%  Lancer depuis le dossier matlab/simul3 :
%      run('create_model3.m')
%
%  Défauts par rapport à simul2 :
%    1. eps_capteur = +0.03  (+3 % d'erreur d'échelle)
%    2. bruit capteur  = 2 mg_rms  (au lieu de 0,5 mg)
%
%  Architecture identique à simul2 :
%    acc_reelle → [Capteur_IEPE] → [PGA] → [AAF] → [ZOH] → [Quantizer]
%                                                              ↓
%                                        acc_mesuree ← [V2g×invG] ← [FIR_Dec]
%
%  PGA_SW : double-cliquer pour commuter mode vibration (×10) / choc (×1)

model_name = 'simul3';

%% Fermer si déjà ouvert
if bdIsLoaded(model_name)
    close_system(model_name, 0);
end

%% Créer et ouvrir le modèle
new_system(model_name);
open_system(model_name);

%% Configuration du solveur
set_param(model_name, ...
    'SolverType',             'Fixed-step', ...
    'Solver',                 'ode4', ...
    'FixedStep',              num2str(1/5000), ...
    'StopTime',               '600', ...
    'InitFcn',                'init3', ...
    'StopFcn',                'stop3', ...
    'ReturnWorkspaceOutputs', 'off');

%% ── Bloc From Workspace : acc_reelle ─────────────────────────────────────
add_block('simulink/Sources/From Workspace', [model_name '/acc_reelle'], ...
    'VariableName', 'acc_reelle', ...
    'SampleTime',   '-1', ...
    'Position',     [50 110 130 140]);

%% ── Sous-système Capteur_IEPE ────────────────────────────────────────────
add_block('simulink/Ports & Subsystems/Subsystem', ...
    [model_name '/Capteur_IEPE'], ...
    'Position', [200 95 400 165]);

sub = [model_name '/Capteur_IEPE'];

% Vider le contenu par défaut
blks = find_system(sub, 'SearchDepth', 1, 'type', 'block');
for i = 1:length(blks)
    if ~strcmp(blks{i}, sub)
        delete_block(blks{i});
    end
end
lns = find_system(sub, 'FindAll', 'on', 'type', 'line');
delete_line(lns);

add_block('simulink/Sources/In1',  [sub '/In1'],  'Position', [30  120  60  150]);
add_block('simulink/Math Operations/Gain', [sub '/K_s'], ...
    'Gain',     'K_s', ...
    'Position', [110 115 180 155]);
% Gain erreur d'échelle (1 + eps_capteur)  ← DÉFAUT 1
add_block('simulink/Math Operations/Gain', [sub '/Echelle'], ...
    'Gain',     '1 + eps_capteur', ...
    'Position', [220 115 330 155]);
add_block('simulink/Continuous/Transfer Fcn', [sub '/HP_IEPE'], ...
    'Numerator',   '[tau_IEPE 0]', ...
    'Denominator', '[tau_IEPE 1]', ...
    'Position',    [370 110 480 160]);
% Bruit dégradé ← DÉFAUT 2 (bruit_capteur_power calculé dans init3)
add_block('simulink/Sources/Band-Limited White Noise', [sub '/Bruit'], ...
    'Cov',      'bruit_capteur_power', ...
    'Ts',       num2str(1/5000), ...
    'Seed',     '1234', ...
    'Position', [370 210 480 250]);
add_block('simulink/Math Operations/Add', [sub '/Add'], ...
    'Inputs',   '++', ...
    'Position', [530 115 570 205]);
add_block('simulink/Sinks/Out1', [sub '/Out1'], 'Position', [630 145 660 175]);

add_line(sub, 'In1/1',     'K_s/1',      'autorouting', 'on');
add_line(sub, 'K_s/1',     'Echelle/1',  'autorouting', 'on');
add_line(sub, 'Echelle/1', 'HP_IEPE/1',  'autorouting', 'on');
add_line(sub, 'HP_IEPE/1', 'Add/1',      'autorouting', 'on');
add_line(sub, 'Bruit/1',   'Add/2',      'autorouting', 'on');
add_line(sub, 'Add/1',     'Out1/1',     'autorouting', 'on');

%% ── PGA (Amplificateur à Gain Programmable) ──────────────────────────────
%   Manual Switch : commuter vibration (G_pga_vib=10) / choc (G_pga_choc=1)
%   Position 0 (haut) = vibration   Position 1 (bas) = choc

add_block('simulink/Sources/Constant', [model_name '/G_vib'], ...
    'Value',    'G_pga_vib', ...
    'Position', [430 35 480 55]);

add_block('simulink/Sources/Constant', [model_name '/G_choc'], ...
    'Value',    'G_pga_choc', ...
    'Position', [430 70 480 90]);

add_block('simulink/Signal Routing/Manual Switch', [model_name '/PGA_SW'], ...
    'sw',       '0', ...        % 0 → G_vib (vibration par défaut)
    'Position', [510 30 550 95]);

% Branche signal × G_pga
add_block('simulink/Math Operations/Product', [model_name '/PGA'], ...
    'Inputs',   '**', ...
    'Position', [580 105 620 145]);

% Branche 1/G_pga (pour la reconversion en sortie)
add_block('simulink/Math Operations/Math Function', [model_name '/invG'], ...
    'Operator', 'reciprocal', ...
    'Position', [510 175 550 215]);

%% ── Filtre anti-repliement analogique (AAF) ──────────────────────────────
%   Butterworth analogique 4 pôles, f_c = 500 Hz
add_block('dspfdesign/Analog Filter Design', [model_name '/AAF'], ...
    'method',   'Butterworth', ...
    'filttype', 'Lowpass', ...
    'N',        'ordre_aaf', ...
    'Wlo',      'omega_aaf', ...
    'Position', [650 100 800 165]);

%% ── CAN 16 bits : ZOH + Quantizer ────────────────────────────────────────
%   ZOH : échantillonnage à fs = 5000 Hz
%   Quantizer : LSB_V = 2*Vref_adc / 2^16  (entrée ADC après PGA)
add_block('simulink/Discrete/Zero-Order Hold', [model_name '/ZOH'], ...
    'SampleTime', '1/fs', ...
    'Position',   [840 110 910 150]);

add_block('simulink/Discontinuities/Quantizer', [model_name '/Quantizer'], ...
    'QuantizationInterval', 'LSB_V', ...
    'Position',             [950 110 1020 150]);

%% ── Décimateur FIR (10:1) ────────────────────────────────────────────────
%   Parks-McClellan, 290 coefficients, 5000 Hz → 500 Hz
add_block('dspmlti4/FIR Decimation', [model_name '/FIR_Dec'], ...
    'h',       'h_dec', ...
    'D',       'M_dec', ...
    'framing', 'Allow multirate processing', ...
    'Position', [1060 110 1160 150]);

%% ── Reconversion tension → accélération : ÷K_s puis ÷G_pga ─────────────
add_block('simulink/Math Operations/Gain', [model_name '/V2g'], ...
    'Gain',     '1/K_s', ...
    'Position', [1200 110 1270 150]);

add_block('simulink/Math Operations/Product', [model_name '/V2g_Prod'], ...
    'Inputs',   '**', ...
    'Position', [1310 110 1360 150]);

%% ── To Workspace : acc_mesuree ───────────────────────────────────────────
add_block('simulink/Sinks/To Workspace', [model_name '/acc_mesuree_ws'], ...
    'VariableName',  'acc_mesuree', ...
    'MaxDataPoints', 'inf', ...
    'SaveFormat',    'Array', ...
    'Position',      [1400 110 1500 150]);

%% Connexions niveau supérieur
add_line(model_name, 'acc_reelle/1',    'Capteur_IEPE/1',  'autorouting', 'on');
add_line(model_name, 'Capteur_IEPE/1', 'PGA/1',            'autorouting', 'on');
add_line(model_name, 'G_vib/1',        'PGA_SW/1',         'autorouting', 'on');
add_line(model_name, 'G_choc/1',       'PGA_SW/2',         'autorouting', 'on');
add_line(model_name, 'PGA_SW/1',       'PGA/2',            'autorouting', 'on');
add_line(model_name, 'PGA_SW/1',       'invG/1',           'autorouting', 'on');
add_line(model_name, 'PGA/1',          'AAF/1',            'autorouting', 'on');
add_line(model_name, 'AAF/1',          'ZOH/1',            'autorouting', 'on');
add_line(model_name, 'ZOH/1',          'Quantizer/1',      'autorouting', 'on');
add_line(model_name, 'Quantizer/1',    'FIR_Dec/1',        'autorouting', 'on');
add_line(model_name, 'FIR_Dec/1',      'V2g/1',            'autorouting', 'on');
add_line(model_name, 'V2g/1',          'V2g_Prod/1',       'autorouting', 'on');
add_line(model_name, 'invG/1',         'V2g_Prod/2',       'autorouting', 'on');
add_line(model_name, 'V2g_Prod/1',     'acc_mesuree_ws/1', 'autorouting', 'on');

%% ── Zones visuelles (Group Using Area) ───────────────────────────────────
add_block('built-in/Area', [model_name '/Capteur IEPE - Kistler 8792A100'], ...
    'Position',        [195 85 410 175], ...
    'ForegroundColor', 'blue', ...
    'BackgroundColor', 'lightBlue');

add_block('built-in/Area', [model_name '/PGA - AD8253'], ...
    'Position',        [425 20 635 225], ...
    'ForegroundColor', 'darkGreen', ...
    'BackgroundColor', 'lightGreen');

add_block('built-in/Area', [model_name '/AAF - Butterworth 4 poles, fc=500 Hz'], ...
    'Position',        [645 90 810 175], ...
    'ForegroundColor', '[0.75 0.5 0]', ...
    'BackgroundColor', 'yellow');

add_block('built-in/Area', [model_name '/Echantillonneur bloqueur + Quantificateur - AD7606-4'], ...
    'Position',        [835 95 1030 165], ...
    'ForegroundColor', 'red', ...
    'BackgroundColor', '[1 0.8 0.8]');

add_block('built-in/Area', [model_name '/Decimateur FIR 10:1 - reconversion g'], ...
    'Position',        [1055 95 1375 165], ...
    'ForegroundColor', '[0.5 0 0.5]', ...
    'BackgroundColor', '[0.9 0.8 1]');

%% Sauvegarde
save_system(model_name);
fprintf('\nModèle "%s.slx" créé et sauvegardé.\n', model_name);
fprintf('Entrée : acc_reelle (g)\n');
fprintf('Sortie : acc_mesuree (g, 500 Hz)\n');
fprintf('Défauts actifs :\n');
fprintf('  1. Erreur d''échelle capteur : eps_capteur = +3 %%\n');
fprintf('  2. Bruit capteur dégradé   : 2 mg_rms  (simul2 : 0,5 mg)\n');
fprintf('PGA_SW : double-cliquer pour commuter vibration (×%g) / choc (×%g)\n', ...
        G_pga_vib, G_pga_choc);
